export default {
    CREATE_COURSE: 'CREATE_COURSE',
    COURSE: "COURSE",
    CREATE: "CREATE_",
    LOAD_COURSES_SUCCESS: "LOAD_COURSES_SUCCESS",
    LOAD_AUTHOR_SUCCESS: "LOAD_AUTHOR_SUCCESS",
    CREATE_COURSE_SUCCESS: "CREATE_COURSE_SUCCESS",
    UPDATE_COURSE_SUCCESS: "UPDATE_COURSE_SUCCESS",
    BEGIN_API_CALL: 'BEGIN_API_CALL',
    API_CALL_ERROR: 'API_CALL_ERROR',
}
